/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_tis_stc_julius_JuliusActivity */

#ifndef _Included_jp_co_tis_stc_julius_JuliusActivity
#define _Included_jp_co_tis_stc_julius_JuliusActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_co_tis_stc_julius_JuliusActivity_SAMPLING_RATE
#define jp_co_tis_stc_julius_JuliusActivity_SAMPLING_RATE 22050L
/*
 * Class:     jp_co_tis_stc_julius_JuliusActivity
 * Method:    initJulius
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_tis_stc_julius_JuliusActivity_initJulius
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_co_tis_stc_julius_JuliusActivity
 * Method:    recognize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_co_tis_stc_julius_JuliusActivity_recognize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_co_tis_stc_julius_JuliusActivity
 * Method:    terminateJulius
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_co_tis_stc_julius_JuliusActivity_terminateJulius
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
