/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_tis_stc_julius_JuliusActivity_JuliusInitializer */

#ifndef _Included_jp_co_tis_stc_julius_JuliusActivity_JuliusInitializer
#define _Included_jp_co_tis_stc_julius_JuliusActivity_JuliusInitializer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
